import "./globals.css"
import { Inter } from "next/font/google"
import { ChakraProvider } from "@chakra-ui/react"
import NavigaitonBar from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Anime LK 23",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <ChakraProvider>
          <NavigaitonBar />
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
