import "src/style/globals.css"
import { Inter } from "next/font/google"
import Nav from "@/components/Nav"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Anime LK 23",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
